version: "2"
services:
# php服务
  php:
    image: php:7.2.3-fpm
    networks:
      - lnmp
    volumes:
       -  ./web:/web
    environment: 
      - TZ=Asia/Shanghai
# nginx服务
  nginx:
    image: nginx:1.13
    networks:
      - lnmp
    ports:
      - 80:80
    volumes:
      - ./web:/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment: 
      - TZ=Asia/Shanghai
    links:
      - php
# mysql服务
  mysql:
    hostname: mysql
    image: mysql:5.6
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      - lnmp
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 666666
# git
  git:
    image: xjx00/gitlab-ce-zh:11.3.0
    ports: 
      - 4430:443
      - 8000:80
      
    volumes:
      - /home/ubuntu/gitlab/config:/etc/gitlab
      - /home/ubuntu/gitlab/log:/var/log/gitlab
      - /home/ubuntu/gitlab/data:/var/opt/gitlab
# 编排工具      
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 9000:9000
networks:
  lnmp: